name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.0'
          cache: true

      # ترفند نهایی: تغییر نسخه گریدل در فایل تنظیمات قبل از شروع بیلد
      - name: Force Gradle 8.2 Upgrade
        run: |
          sed -i 's/gradle-8.0-all.zip/gradle-8.2-all.zip/g' android/gradle/wrapper/gradle-wrapper.properties
          sed -i 's/gradle-8.0-bin.zip/gradle-8.2-all.zip/g' android/gradle/wrapper/gradle-wrapper.properties

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release-release.apk
